### ISSUE TITLE
How to get the 2D bboxes from 3D bboxes, in the Online Single frame Experiemnet?

### ISSUE THREAD

**Issue by moaljazaery** [apple/ARKitScenes#9]
Thanks for releasing this fruitful  dataset. 
 I am trying to train a 2D object detector. How can I get the 2D BBOX? What is  "urc" coordinate that you are using in "data_prepare_online.py"?

**Comment by PeterZheFu** [comment]
Hi @moaljazaery,
    Thanks for your interest and reaching out. Sorry for my belated reply.
    Unfortunately, at this point, we have not included a helper function to project 3D BBoTo get 2D BBOX. 
    However, there are open source methods where you would can do so via camera pose. We have included the camera pose for each frame in our 3dod data directory. 
    The "urc" coordinate is used in single-frame 3dod, where we rotate the point cloud to be gravity aligned.
Thanks,
Peter

**Comment by PeterZheFu** [comment]
Closing the issue for now. Feel free to re-open it if you have any further questions~

**Comment by M-G-A** [comment]
Sorry for opening the issue again. But I thought maybe someone is interested in a quick solution:
https://github.com/M-G-A/ARKitScenes/blob/main/threedod/benchmark_scripts/utils/tenFpsDataLoader.py

I slightly changed the loader in order to generate the masks on the fly only using the depth map, but not the fused point cloud. This may lead to some error. 
Here I generate binary masks. However, generating the boxes from them shouldn't be too hard for you ;).

The masks itself neglect that objects overlap. Which sometimes even can be better for training...
If you are interested in how to generate it in a more sophisticated way with considering the overlap, you can contact me. (I did this once for another dataset) 

Attached is an example image, where all masks are plotted on the same image, so you can see the overlapping issue:
![overlapping_masks](https://user-images.githubusercontent.com/769780/190400726-f28e22f6-57e4-458e-9515-195ab0e16dbb.png)
